import sys

from PyQt5 import Qt, uic, QtWidgets, QtCore
from PyQt5.QtCore import Qt, QPoint
from PyQt5.QtGui import QPainter, QColor, QPolygon
from PyQt5.QtWidgets import QWidget, QApplication, QLabel, QMainWindow, QPushButton
from random import randint as rd


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(629, 728)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(160, 180, 25, 19))
        self.toolButton.setObjectName("toolButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 50, 171, 128))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.p1_numb = QtWidgets.QSpinBox(self.widget)
        self.p1_numb.setObjectName("p1_numb")
        self.verticalLayout.addWidget(self.p1_numb)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout.setStretch(3, 40)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 171, 41))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_nat = QtWidgets.QLabel(self.widget1)
        self.label_nat.setTextFormat(QtCore.Qt.AutoText)
        self.label_nat.setScaledContents(False)
        self.label_nat.setWordWrap(False)
        self.label_nat.setObjectName("label_nat")
        self.horizontalLayout.addWidget(self.label_nat)
        self.p1_nations = QtWidgets.QComboBox(self.widget1)
        self.p1_nations.setEnabled(True)
        self.p1_nations.setEditable(False)
        self.p1_nations.setPlaceholderText("")
        self.p1_nations.setDuplicatesEnabled(False)
        self.p1_nations.setFrame(False)
        self.p1_nations.setObjectName("p1_nations")
        self.p1_nations.addItem("")
        self.p1_nations.addItem("")
        self.p1_nations.addItem("")
        self.p1_nations.addItem("")
        self.p1_nations.addItem("")
        self.p1_nations.addItem("")
        self.p1_nations.addItem("")
        self.p1_nations.addItem("")
        self.p1_nations.addItem("")
        self.p1_nations.addItem("")
        self.horizontalLayout.addWidget(self.p1_nations)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_5)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.comboBox.setItemText(0, _translate("MainWindow", "Все (Тип техники)"))
        self.comboBox.setItemText(1, _translate("MainWindow", "ЛТ"))
        self.comboBox.setItemText(2, _translate("MainWindow", "СТ"))
        self.comboBox.setItemText(3, _translate("MainWindow", "ТТ"))
        self.comboBox.setItemText(4, _translate("MainWindow", "ПТ"))
        self.comboBox.setItemText(5, _translate("MainWindow", "ЗСУ(ЗРК)"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Все (ЛВЛ\'А)"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "I"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "II"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "III"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "IV"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "V"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "VI"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "VII"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.label_nat.setText(_translate("MainWindow", "Нация"))
        self.p1_nations.setCurrentText(_translate("MainWindow", "Не выбрано"))
        self.p1_nations.setItemText(0, _translate("MainWindow", "Не выбрано"))
        self.p1_nations.setItemText(1, _translate("MainWindow", "США"))
        self.p1_nations.setItemText(2, _translate("MainWindow", "СССР"))
        self.p1_nations.setItemText(3, _translate("MainWindow", "Германия"))
        self.p1_nations.setItemText(4, _translate("MainWindow", "Великобритания"))
        self.p1_nations.setItemText(5, _translate("MainWindow", "Япония"))
        self.p1_nations.setItemText(6, _translate("MainWindow", "Китай"))
        self.p1_nations.setItemText(7, _translate("MainWindow", "Италия"))
        self.p1_nations.setItemText(8, _translate("MainWindow", "Франция"))
        self.p1_nations.setItemText(9, _translate("MainWindow", "Швеция"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.action.setText(_translate("MainWindow", "Сохранить настройки"))
        self.action_2.setText(_translate("MainWindow", "Загрузить настройки"))
        self.action_4.setText(_translate("MainWindow", "Выбрать технику"))
        self.action_5.setText(_translate("MainWindow", "Сохранить технику"))


class Example(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.toolButton.setMenu(menu_items,)

        self.menu_items = [
            {'Source': ['google', 'yahoo', 'Reuters', ]},
            'test1',
            'test2',
            'test3',
        ]




if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = Example()
    ex.show()
    sys.exit(app.exec())